// convert_binary_output_file_to_ascii.c
// (c) 2023, Leo Werneck
//
// This program can be used to convert binary output files
// generated by particle_tracerET to ASCII files.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libgen.h>
#include <unistd.h>

int main(int argc, char **argv) {

  if(argc != 2) {
    fprintf(stderr, "Correct usage is: %s <filename>\n", argv[0]);
    exit(1);
  }

  char filename_in[1024], filename_out[1024];
  sprintf(filename_in, "%s", argv[1]);

  if( strcmp(filename_in+strlen(filename_in)-4, ".bin") ) {
    fprintf(stderr, "Warning: Expected an input file (%s) with a '.bin' extension.\n", filename_in);
    fprintf(stderr, "Warning: Output file name will probably be strange.\n");
  }

  char *cwd = getcwd(filename_out, sizeof(filename_out));
  sprintf(filename_out, "%s/%s", cwd, basename(filename_in));
  size_t n = strlen(filename_out);
  filename_out[n-4] = '.';
  filename_out[n-3] = 'a';
  filename_out[n-2] = 's';
  filename_out[n-1] = 'c';  
  
  FILE *fp_in  = fopen(filename_in , "rb");
  FILE *fp_out = fopen(filename_out, "w");

  int num_quantities;
  n = fread(&num_quantities, sizeof(int), 1, fp_in);

  int num_particles;
  n = fread(&num_particles, sizeof(int), 1, fp_in);

  size_t ntotal    = num_quantities*num_particles;
  double time;
  double *arrays   = (double *)malloc(sizeof(double)*ntotal);
  char *buffer     = (char *) malloc(sizeof(char)*5000000); // <- Allocate 5MB; sizeof(char) is 1.
  char *timebuffer = (char *)malloc(sizeof(char)*5000000); // <- Allocate 5MB; sizeof(char) is 1.
  timebuffer[0] = '\0';
  
  while( fread(&time , sizeof(double), 1     , fp_in)==1 &&
         fread(arrays, sizeof(double), ntotal, fp_in)==ntotal ) {
    sprintf(buffer, "%e", time);
    sprintf(timebuffer, "%s %g", timebuffer, time);
    for(int i=0;i<num_particles;i++)
      for(int j=0;j<num_quantities;j++)
        sprintf(buffer, "%s %e", buffer, arrays[i + j*num_particles]);
    fprintf(fp_out, "%s\n", buffer);
  }
  
  fclose(fp_in);
  fclose(fp_out);
  free(arrays);

  printf("Basic information\n");
  printf("-----------------\n");
  printf("  Input file           : %s\n", filename_in);
  printf("  Output file          : %s\n", filename_out);
  printf("  Number of particles  : %d\n", num_particles);
  printf("  Number of quantities : %d\n", num_quantities);
  printf("  Available times      :%s\n", timebuffer);

  return 0;
}
